<section class="services-details-wrapper section-padding">
    <div class="container">
        <div class="col-lg-10 col-12 offset-lg-1">

            @if(Auth::user())
                @can('page check')
                    <div class="easier-mode">
                        @if(Auth::user())
                            @can('page check')
                                <!-- hover effect for mobile devices  -->
                                <div class="click-icon d-md-none text-center">
                                    <button class="custom-btn text-white">
                                        <i class="fa fa-mobile-alt text-white"></i> {{ __('content.touch') }}
                                    </button>
                                </div>
                            @endcan
                        @endif
                        <div class="easier-section-area">
                            @endcan
                            @endif

                            @isset ($page)
                                <div class="services-contents">
                                    @if (!empty($page->section_image))
                                        <img src="{{ asset('uploads/img/page/'.$page->section_image) }}" alt="page image" class="img-fluid">
                                    @endif
                                    <p class="mt-4">@php echo html_entity_decode($page->description); @endphp</p>
                                </div>
                            @else
                                @if (Auth::user() || $draft_view == null || $draft_view->status == 'enable')
                                    <div class="services-contents">
                                        <img src="{{ asset('uploads/img/dummy/1080x540.jpg') }}" alt="career image">

                                        <p class="mt-4"><b>An automated report is a management tool used by professionals to create and share business reports at a specific time  information each time. These updates are usually made in real-time with the help of automated reporting tools.</b></p>

                                        <p class="mt-4">Data, information, and insights are all around us. Before we even realize our business potentials and  in our competitive market, there is always a new business plan to make, a new strategy to develop, a new report to generate - and they all take time. Since amounts of data are generated by every second, businesses are always on the lookout for the best possible online data analysis tools  make their processes easier, faster, and more effective.</p>
                                        <p class="mt-4">Productivity has become the epitome of successful business processes. While every manager seeks how to increase productivity and decrease business costs, some invaluable processes can push towards sustainable business development - automated reportin and systems are the answer you've been looking for.</p>
                                        <p class="mt-4">That said, in this post, we will explain what is an automated report and its benefits, the ins and outs of the automat process, and finish with examples from the real business world. After reading this article, you will be equipped to create your own automation practic and upscale your reports with the help of a modern online reporting software.</p>

                                        <p class="mt-4"><b>The process of making our automated reporting work</b></p>
                                        <p class="mt-4">The manufacturing industry needs continuous automation throughout processes, and each part of the company needs to work flawlessly in order to avoid potential business issues and cost increment.</p>
                                    </div>
                                @endif
                            @endisset

                            @if(Auth::user())
                                @can('page check')
                        </div>
                        <div class="easier-middle">
                            @php
                                $url = request()->path();
                                $modified_url = str_replace('/', '-bracket-', $url);
                            @endphp
                            <form method="POST" action="{{ route('site-url.index') }}" class="d-inline-block">
                                @csrf
                                <input type="hidden" name="route" value="page.edit">
                                <input type="hidden" name="style" value="{{ $page->id }}">
                                <input type="hidden" name="site_url" value="{{ $modified_url }}">
                                <button type="submit" class="custom-btn text-white me-2">
                                    <i class="fa fa-edit text-white"></i> {{ __('content.edit_page') }}
                                </button>
                            </form>

                        </div>

                    </div>
                @endcan
            @endif

        </div>
    </div>
</section>


